### GET request to example server
GET http://localhost:8080

###
GET http://localhost:8080/api/software-engineers

###
GET http://localhost:8080/api/software-engineers/1

###
POST http://localhost:8080/api/software-engineers
Content-Type: application/json


{
  "name": "test",
  "techStack": "testing, API"
}

###
PUT http://localhost:8080/api/software-engineers/2
Content-Type: application/json


{
"name": "Treasure",
"techStack": "React, Tailwind"
}


###
DELETE http://localhost:8080/api/software-engineers/8